### ISSUE TITLE
Mod failes to start

### ISSUE THREAD

**Issue by meo209** [Polyfrost/OneConfigExampleMod#6]
When launching the example mod, a java error shows up:

```java
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

OS: Endevouros Linux
Java Version: 17/8 (either fails)

**Comment by YodaForce157** [comment]
How did you fix this?

**Comment by meo209** [comment]
> How did you fix this?

I don't know anymore, sorry.

I believe it was something with the Java Version.
